SYSTEM_ID = "SV-TGWIFIDJXM946-0000"
APP_VERSION = "2021062201"
CLIENT_ID = "google_client_id"
SYSTEM_KEY = "2fa3c60aa34b806b463088f6e164a32a"
APP_KEY = "08ce72f7c82f1a999cb53fe983acfe74"

DEVICE_TYPE_HVAC = "03001001"


RET_CODE_USER_ILLEGAL = "D00008"
RET_CODE_USER_NOT_MATCH_DEVICE = "130004"
RET_CODE_OK = "00000"


# Device status interpretation
HVAC_STATUS_ON = True
HVAC_STATUS_OFF = False
HVAC_OPERATION_MODE_COOL = 1
HVAC_OPERATION_MODE_DRY = 2
HVAC_OPERATION_MODE_FAN = 6
HVAC_WIND_SPEED_LOW = 3
HVAC_WIND_SPEED_MID = 2
HVAC_WIND_SPEED_HIGH = 1
HVAC_WIND_SPEED_AUTO = 5
HVAC_WIND_DIRECTION_VERTICAL_AUTO = 8
HVAC_WIND_DIRECTION_VERTICAL_FIXED = 0
HVAC_WIND_DIRECTION_HORIZONTAL_AUTO = 7
HVAC_WIND_DIRECTION_HORIZONTAL_FIXED = 0

HVAC_ON_OFF_STATUS = "onOffStatus"
HVAC_OPERATION_MODE = "operationMode"
HVAC_TARGET_TEMP = "targetTemperature"
HVAC_ROOM_TEMP = "indoorTemperature"
HVAC_WIND_SPEED = "windSpeed"
HVAC_WIND_DIRECTION_VERTICAL = "windDirectionVertical"
HVAC_WIND_DIRECTION_HORIZONTAL = "windDirectionHorizontal"
HVAC_HUMAN_SENSING_STATUS = "humanSensingStatus"
HVAC_SELF_CLEANING_STATUS = "selfCleaningStatus"

HVAC_OPERATION_MODE_STR = {
    "Cool": HVAC_OPERATION_MODE_COOL,
    "Dry": HVAC_OPERATION_MODE_DRY,
    "Fan": HVAC_OPERATION_MODE_FAN,
}

HVAC_WIND_SPEED_STR = {
    "Low": HVAC_WIND_SPEED_LOW,
    "Medium": HVAC_WIND_SPEED_MID,
    "High": HVAC_WIND_SPEED_HIGH,
    "Auto": HVAC_WIND_SPEED_AUTO,
}

HVAC_WIND_DIRECTION_VERTICAL_STR = {
    "Auto": HVAC_WIND_DIRECTION_VERTICAL_AUTO,
    "Fixed": HVAC_WIND_DIRECTION_VERTICAL_FIXED,
}

HVAC_WIND_DIRECTION_HORIZONTAL_STR = {
    "Auto": HVAC_WIND_DIRECTION_HORIZONTAL_AUTO,
    "Fixed": HVAC_WIND_DIRECTION_VERTICAL_FIXED,
}
